on:
  pull_request_target:
    types: [ opened, reopened ]

name: "Vouch - Check PR"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ secrets.VOUCH_ID }}
          private-key: ${{ secrets.VOUCH_PRIVATE_KEY }}

      - uses: mitchellh/vouch/action/check-pr@v1
        with:
          pr-number: ${{ github.event.pull_request.number }}
          auto-close: true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}